export const GET_ID = 'GET_ID';
export const GET_FULL_NOTE = 'GET_FULL_NOTE';
export const TITLE_CHANGED = 'TITLE_CHANGED';
export const CONTENT_CHANGED = 'CONTENT_CHANGED';


export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAIL = 'ADD_NOTE_FAIL';
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
export const DELETE_NOTE = 'DELETE_NOTE';
export const EDIT_NOTE_FINISHED = 'EDIT_NOTE_FINISHED';


export const FETCH_NOTES_START = 'FETCH_ORDERS_START';
export const FETCH_NOTES_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_NOTES_FAIL = 'FETCH_ORDERS_FAIL';

export const SEARCH_FILTER = 'SEARCH_FILTER';